- build.cmd
It currently confuses user and the functionality is part of the buildAll.cmds and electronize build
> Remove old build.cmd

- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/Commands/StartElectronCommand.cs
- ElectronNET.WebApp/ElectronNET.WebApp.csproj
- start.cmd
- start.sh
In .NET Core 2.0, generic RID's should be used to enable broadest reach for the resulting published app. This change just moves all the scripts/projects to use that instead.
> Move to generic RIDs

- ElectronNET.CLI/Commands/InitCommand.cs
the idea is to have the minimum amount of change detected in csproj
`<?xml version ...?>`
as never been part of csproj
> use XmlWritter to avoid serialising Xml Declaration in csproj

- README.md
Should never use async void
I tried other scenario but that seems to endup in deadlock or the WebHostBuilder is not happy
I ended up avoiding 
Not working so far:
```csharp
public async Task Configure(IApplicationBuilder app, IHostingEnvironment env)
{
await Electron.WindowManager.CreateWindowAsync()
}
```
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
Electron.WindowManager.CreateWindowAsync().Start()
}
```
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
Electron.WindowManager.CreateWindowAsync().RunSynchronously()
}
```
> Should never use async void

- README.md
Add more detail to the spot in the Readme that currently says "the build just hangs, but I'm not sure why" re: trying to build for macOS on Windows. It turns out this is a fundamental Electron issue they've looked into considerably and have not been able to resolve (other than "make macOS builds on Macs or Linux machines").
> Add link to Readme explaining macOS build issues on Windows Machines

- ElectronNET.API/App.cs
This would add cancellation token support to the async App methods
> App cancellation token

- ElectronNET.CLI/Commands/Actions/GetTargetPlatformInformation.cs
- ElectronNET.CLI/Commands/BuildCommand.cs
Hi,
as discussed in the issue #118 . Direct support for linux-arm added. Platform for packager is still linux. electron-arch gets already piped through correctly.
> added support for linux-arm platform

- ElectronNET.API/Dialog.cs
- ElectronNET.API/ElectronNET.API.csproj
- ElectronNET.API/IpcMain.cs
- ElectronNET.CLI/ElectronNET.CLI.csproj
- ElectronNET.CLI/ProcessHelper.cs
- ElectronNET.Host/api/app.js
- ElectronNET.Host/api/browserWindows.js
- ElectronNET.Host/api/clipboard.js
- ElectronNET.Host/api/dialog.js
- ElectronNET.Host/api/globalShortcut.js
- ElectronNET.Host/api/ipc.js
- ElectronNET.Host/api/menu.js
- ElectronNET.Host/api/notification.js
- ElectronNET.Host/api/screen.js
- ElectronNET.Host/api/shell.js
- ElectronNET.Host/api/tray.js
- ElectronNET.Host/api/webContents.js
- ElectronNET.Host/main.js
when io reconnect, a new socket well create.
but from front socket not be updated
the commit is fix it by global.elesocket
please check, or better method
> fix: socket.connnect JS : Scope & Closures

- .travis.yml
- ElectronNET.CLI/ElectronNET.CLI.csproj
- ElectronNET.WebApp/ElectronNET.WebApp.csproj
- NuGet.config
- buildAll.cmd
- buildAll.sh
Moving from the "old" way to the new proposed dotnet tool world.
Will enable us to install "electronize" on as a "global dotnet tool".
e.g. just invoke it from the cmd via "electronize ..."
> CLI is now a dotnet tool

- Changelog.md
- ElectronNET.CLI/Commands/BuildCommand.cs
> npm install without prod flag

- ElectronNET.CLI/ProcessHelper.cs
Fixes #160
The problem is that `ng build` logs lines like the following:
```
20% building modules 90/102 modules 12 active 
...modules\\rxjs\\_esm5\\util\\EmptyError.js
```
The original code detects this as an error, unintentionally. The problem is compounded by the fact that the build process uses backspace characters, which means the "offending" line is invisible to end users.
This fix doesn't address the fact that scanning for "error" is a horrible hack, but I'm sure you've already explored the alternatives. Instead, I've made the smallest change possible that will continue to detect any likely error, while ignoring these problematic files. Fortunately, no file called "error.js" is installed, at least when I tested (Windowx x64, netcoreapp**2.1**, default new angular project).
> Reduce chance of detecting false positives when scanning subprocesses for errors.

- ElectronNET.CLI/Commands/InitCommand.cs
- ElectronNET.WebApp/Properties/launchSettings.json
I've noticed that when calling **electronize init**
The default behaviour is to modify launchSettings.json to add a profile to launch electronize via dotnet
However this would only work if electronize.exe was renamed to dotnet-electronize.exe in the tools directory
I've modified the init routine and the launchSettings.json of the example web app
to instead call electronize directly from the Path
Typically under windows it's located under C:\Users\UserName\\.dotnet\tools\electronize.exe
which seems to be on my path by default.
For info the WorkingDirectory parameter of "." is needed to place the working directory in the same directory as the .csproj file instead of somewhere inside a bin/Debug folder.
The only other way to fix this would be to rename electronize.exe to …
> Call electronize from the Path instead of via dotnet in launchSettings.json

- ElectronNET.API/Entities/WebPreferences.cs
- ElectronNET.API/WebHostBuilderExtensions.cs
- README.md
- buildReleaseNuGetPackages.cmd
_Why this change?_
Default behavior for windows appears to be to resolve ```localhost``` to ```0.0.0.0``` which causes the Windows firewall to get triggered, but also exposes the ASP.NET backend to remote access which opens up the app to RCE risks unnecessarily.
_Also_
1. Add a comment for why NodeIntegration is true.
2. The version used in the build script is now a variable, only needs to be changed once.
I've validated that with this changed behavior, our App, [Attack Surface Analyzer](github.com/Microsoft/AttackSurfaceAnalyzer), encounters no issues. I'm unable to test it on the WebApp as the version on master currently does not work for me (even without my changes).
> Fix ASP.NET backend listening on 0.0.0.0

- ElectronNET.API/ElectronNET.API.csproj
- ElectronNET.CLI/ElectronNET.CLI.csproj
- ElectronNET.WebApp/ElectronNET.WebApp.csproj
I discovered that our libs are targeting netcoreapp2.1 instead of netcoreapp2.2. 
It should be "ok", but not sure if someone with ASP.NET Core 2.1 is using our lib.
> update projects to use netcoreapp2.2

- Changelog.md
- ElectronNET.Host/api/tray.js
- ElectronNET.Host/api/tray.ts
- ElectronNET.WebApp/Controllers/TrayController.cs
- ElectronNET.WebApp/ElectronNET.WebApp.csproj
The main idea is: the developer of the end-user application should take care of the tray icon path, not the ElectronNET framework.
> Fixed bug: Electron tray icon TypeError

- ElectronNET.Host/main.js
- buildReleaseNuGetPackages.sh
Solves https://github.com/ElectronNET/Electron.NET/issues/261
> fix async issue where same port is considered open

- ElectronNET.API/BrowserWindow.cs
- ElectronNET.Host/api/browserWindows.js
- ElectronNET.Host/api/browserWindows.ts
Fixes issue #301 by adding Electron API [win.removeMenu()](https://electronjs.org/docs/api/browser-window#winremovemenu-linux-windows), extending Electron.NET API by adding `BrowserWindow.RemoveMenu()` method
> fix issue #301

- buildAll.cmd
- buildAll.sh
This is followup to c91884a5203c8f1f14c7320595126b1bbe60f68e change which on itself was reaction to electron-builder changes in the command line parameters interface
Close #320
> Fix `buildAll.cmd` and `buildAll.sh` when running on clear repo

- .travis.yml
- ElectronNET.CLI/Commands/AddCommand.cs
- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/Commands/StartElectronCommand.cs
- README.md
- appveyor.yml
These changes remove the need to either A) install tools globally (`typescript` and `electron-builder`) and B) call tools locally via actual path (some `tsc` calls find the bin path first).
This should avoid any differences between platforms but I haven't been able to test it on every platform (just Windows for now). I should be able to run some tests on Linux this weekend.
See [my comment](https://github.com/ElectronNET/Electron.NET/pull/313#issuecomment-545256352) on #313 for more details.
> Converted global npm dependencies to use npx

- ElectronNET.WebApp/Program.cs
It essentially the same as before, but MVC test tooling expect Program to have CreateWebHostBuilder. I referer to ability to seamlessly use WebApplicationFactory
I understand that story for testing Electron application will be not easy as it is, but this is allow better defaults for testing web applications which can be run in hybrid mode.
> Change test application initialization procedure.

- ElectronNET.Host/main.js
excluding the already used port for lookup, so no race condition can happen on the used electron port
> #308 - Start process with listen port 8000 error.

- Changelog.md
- ElectronNET.CLI/Commands/BuildCommand.cs
Ran into this myself today, if a user fails to provide the `/target` argument when running `electronize build` they simply get a `KeyNotFoundException`.
This change checks for the presence of this argument and, if not present, displays help information to the user as well as gracefully exiting.
Related to https://github.com/ElectronNET/Electron.NET/issues/296
As a sidenote, is there a reason we don't use a command line parsing library (for example - https://github.com/commandlineparser/commandline) to handle these cases for us?
> Handle missing `/target` argument for `build` command.

- ElectronNET.API/Entities/NotificationOptions.cs
Good news, all properties, methods of notifications are now included. The bad news is, the property that should fixed #408 cannot be used at the moment because the implementation in electron is [bugged](https://github.com/electron/electron/issues/22192).
> Added missing properties in Notifications

- ElectronNET.API/NativeTheme.cs
- ElectronNET.CLI/Commands/StartElectronCommand.cs
- ElectronNET.CLI/Properties/launchSettings.json
ElectronNET.API:
- Fixed a typo in a NativeTheme summary.
ElectronNET.CLI
- Fixed bug: Custom user path removed and replaced by the correct directory with VS macro
- New Feature: Set configuration profile [Default Release] #407 
`electronize start /dotnet-configuration Release'
When ElectronNET.CLI is the Startup Project, press F5 (Debzg) and the ElectronNET.WebApp starts correctly without error!
> Add missing config parameter fixes #407

- ElectronNET.API/App.cs
- ElectronNET.API/LifetimeServiceHost.cs
- ElectronNET.API/WebHostBuilderExtensions.cs
- ElectronNET.CLI/Properties/launchSettings.json
- ElectronNET.WebApp/Controllers/MenusController.cs
- ElectronNET.WebApp/Startup.cs
The new property indicates when the ASP.NET Core host is fully started. The validation is done directly in the API so that the user does not have to do this himself. See before and after MenuController  [example](https://github.com/ElectronNET/Electron.NET/commit/52b850092ce99eda56b45f41bcb63a9b542f2004).
> New App.IsReady property

- ElectronNET.CLI/Commands/BuildCommand.cs
Fixes #441
I removed the extra "." in the ProcessHelper.CmdExecute(...) function in the BuildCommand.cs
This should fix the issue in #441
> Bug Fix, Fixed Publishing Issue ("Unknown argument: .")

- ElectronNET.API/Tray.cs
- ElectronNET.Host/api/tray.js
- ElectronNET.Host/api/tray.ts
This allows empty tray icon to be placed without a context menu. Useful for cases when only minimize/close to tray is implemented.
This somehow also fixes menu icon click events in macOS. (probably a thing in base electronjs as well). Not sure about other OS though.
> Enabled empty tray icon

- README.md
The README.md file still referenced the old 8.31.1 version of the ElectronNET.CLI.
This is just a documentation change for clarity.  
This PR updates the README.md to reference the lastest tooling as of Monday, July 6, 2020, at 19:06:12 UTC.
**Old Version**
**New Version**
> Update Documentation in the README.md

- ElectronNET.CLI/Commands/AddCommand.cs
- ElectronNET.CLI/Commands/InitCommand.cs
Resolution to problem with init command for F# ASP.NET Core projects.
Update the projects searched for to include both `.csproj` and `.fsproj`, and update the print statements to reflect both project types.
Fixes #452
> Search for .csproj and .fsproj in init and add commands

- buildAll.sh
There are two issues:
- the original directory is not restored after it is invoked - I have used pushd/popd
- #464 the win/osx builds fail on linux - I have disabled them if it's linux - I don't know if they work on osx
> buildAll.sh linux errors

- ElectronNET.API/Entities/WebPreferences.cs
Fix regression of #345 where the default font size is overridden when the window position is set on creation.
> set default WebPreferences.DefaultFontSize

- ElectronNET.API/App.cs
- ElectronNET.Host/main.js
- buildAll.sh
Added support for launching the application with a file on MacOS by listening for the open-file and open-url events from the operating system, and forwarding them to the Electron.NET app when listeners are added
> Added support for launching the application with a file on MacOS

- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/Commands/StartElectronCommand.cs
Added new /publishSingleFile [true|false] parameter to build and start commands, this adds value for developers that would prefer bundling their webhost project resource as a single executable.
> Added new build and start commandline options for single exe

- ElectronNET.API/ElectronNET.API.csproj
- ElectronNET.CLI/ElectronNET.CLI.csproj
- ElectronNET.WebApp/ElectronNET.WebApp.csproj
Upgraded projects from .NET 3.1 to .NET 5.0.
Upgraded WebApp project from TypeScript 3.8 to TypeScript 5.0.
Upgraded NuGet packages to the latest versions:
- Microsoft.SourceLink.GitHub 1.0.0-beta2-19367-01 > 1.0.0
- System.Drawing.Common 4.7.0 > 5.0.0
- Microsoft.VisualStudio.Web.CodeGeneration.Design 3.0.0 > 5.0.0
This addresses issue #491
> Upgrade to .NET 5

- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/SimpleCommandLineParser.cs
- ElectronNET.Host/package-lock.json
- ElectronNET.Host/package.json
Use `/p:propertyName=value` or `/property:propertyName=value` to pass in property overrides. This is equivalent to the `-p:` option documented here.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish 
fixes #523
> fixes #523 allow for property overrides to be passed in

- ElectronNET.Host/main.js
- ElectronNET.Host/splashscreen/index.html
Resolves #539, #357
Using the `browser-window-focus` event would cause the splashScreen window to be destroyed early (since regular mouse-focus events would cause the event to be fired).
Switching to the `browser-window-created` event produces the correct behavior.
> Resolve #539, #357 - Fix splash screen interaction causing crashes, ghost dragging, and resizable behavior

- ElectronNET.API/Entities/Blob.cs
- ElectronNET.API/Entities/IPostData.cs
- ElectronNET.API/Entities/LoadURLOptions.cs
- ElectronNET.API/Entities/UploadFile.cs
- ElectronNET.API/Entities/UploadRawData.cs
Enable the possibility to post data to external Url's with the BrowserWindow.LoadURL function. The post data is provided through LoadURLOptions
> Add PostData to LoadURLOptions to allow http-posts in LoadURL calls

- ElectronNET.CLI/ProcessHelper.cs
Maybe I didn't take into account something, but I think it will work better.
It fixes my problem with warning in `dotnet publish` output like this:
> ...\Pages\\**Error**.cshtml.cs(13,18): warning SA1649: File name should match first type name.
> Using exit code instead of seek for the term 'error'

- ElectronNET.API/Entities/Vibrancy.cs
Noticed that Vibrancy serialization works incorrect. It may lead to crash on macOS if incorrectly serialized values are used. I've tested it. Application crashed.
Json property attributes are ignored because they are placed too deep. This changes will fix that.
You may read about custom enum values names serialization [here](https://automationrhapsody.com/serialize-and-deserialize-enum-values-to-custom-string-in-c-with-json-net/) (random article about it) or somewhere else.
> Vibrancy serialization fix

- ElectronNET.CLI/Commands/BuildCommand.cs
Adds an additional line of help to explain how publish parameters should be passed to modify the default behavior
> Adds help regarding to modify publish parameters

- ElectronNET.CLI/Commands/BuildCommand.cs
Hi there,
Thanks for this great project so we can build electron app in C# smoothly. I just found a small issue in the build command parsing logic and commit a fix about this.
```
$ electronize build /target
Build Electron Application...
Arguments: 
target = 
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__21_0() in C:\_WorkRepos\Electron.NET\ElectronNET.CLI\Commands\BuildCommand.cs:line 54
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread …
```
> Fix IndexOutOfRangeException in build command parsing logic

- ElectronNET.CLI/Commands/BuildCommand.cs
This was changed before and is also noted in the current changelog. The change was lost during the merge of [Bug 578](https://github.com/ElectronNET/Electron.NET/issues/578)
> Set PublishSingleFile default back to false for NET5 compatibility

- ElectronNET.Host/main.js
I have just used this slightly modified script to debug why my application wasn't starting correctly/at all.
May assist with #571 as I had identical symptoms
> Log errors in the dotnet process

- ElectronNET.CLI/Commands/Actions/GetTargetPlatformInformation.cs
- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/ElectronNET.CLI.csproj
- README.md
While the current version works well with Rosetta 2, it is beneficial to be able to compile natively for ARM/Apple Silicon.
One issue that I would like input on is the switch from dotnet 5 to 6 for the CLI tools. Dotnet 6 is the minimum version to be able to target `osx-arm64` and switching the CLI tools to 6 allows for the tools to be compiled and run natively on arm. The changes that I made should still work fine with dotnet 5 and be able to compile for `osx-arm64` as long as dotnet 6 is also installed. It may also make more sense for this upgrade to be a separate pull request and upgrade all of the projects together to dotnet 6.
> Support Apple Silicon Natively

- ElectronNET.Host/main.js
The Electron app fails when using a self-signed certificate for https communications with its ASP.NET Core backend. The native electron framework allows to ignore or bypass certificate errors. I am exposing this feature to Electron.NET
There will be two ways to bypass certificate errors:
1. By adding this flag to the electron.manifest.json file: `"ignoreAllCertificateErrors": true` it will allow to ignore all cert errors. This option is less secure
2. By adding a list of domain names that we want to ignore certificate errors for in the electron.manifest.json file:
```
"domainNamesToIgnoreCertificateErrors": [
"localhost",
"127.0.0.1",
"www.insecure.site.com"
],
```
> Allow ignoring certificate errors

- ElectronNET.API/ElectronNET.API.csproj
- ElectronNET.API/runtimeconfig.json
- ElectronNET.CLI/Commands/BuildCommand.cs
- ElectronNET.CLI/Commands/StartElectronCommand.cs
- ElectronNET.CLI/ElectronNET.CLI.csproj
- ElectronNET.WebApp/ElectronNET.WebApp.NET5.csproj
- ElectronNET.WebApp/ElectronNET.WebApp.NET6.csproj
- ElectronNET.sln
- README.md
- appveyor.cmd
- appveyor.yml
- buildAll.cmd
- buildAll.sh
- start.cmd
- start.sh
* NET 6 Support
* Target a specific project in the `electronize build/start` command using `/dotnet-project <projectName>.csproj`
NOTE: the .NET6 runtime has targeted System.Drawing.Common at windows architectures and will cause warnings.  This should be addressed at some time.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
> Support for .NET 6

- ElectronNET.API/Entities/BrowserWindowOptions.cs
- ElectronNET.Host/api/browserWindows.js
- ElectronNET.Host/api/browserWindows.ts
> Add ability to set a window's parent using BrowserWindowOptions

- ElectronNET.API/ElectronNET.API.csproj
- ElectronNET.API/Entities/BitmapOptions.cs
- ElectronNET.API/Entities/CreateFromBitmapOptions.cs
- ElectronNET.API/Entities/CreateFromBufferOptions.cs
- ElectronNET.API/Entities/CreateOptions.cs
- ElectronNET.API/Entities/ImageOptions.cs
- ElectronNET.API/Entities/NativeImage.cs
- ElectronNET.API/Entities/NativeImageJsonConverter.cs
- ElectronNET.API/Entities/Size.cs
- ElectronNET.API/Entities/ToBitmapOptions.cs
- ElectronNET.API/Entities/ToDataUrlOptions.cs
- ElectronNET.API/Entities/ToPNGOptions.cs
fixes #637 Conversion to use ImageSharp rather than System.Drawing.Common for cross platform compatibility.
Breaking Changes:
* `System.Drawing.Common` is dropped and `SixLabors.ImageSharp` is introduced.
* uses of `NativeImage.CreateFromBitmap(bitmap, options);` is no longer supported, will cause failed builds.
Unexpected Behaviors:
* uses `ToDataUrl` will always create png data urls, unexpected output may happen for those that manipulate this output expecting a different data url format.
Obsoletions:
* `CreateFromBitmapOptions` & `CreateFromBufferOptions` have been consolidated into `CreateOptions`. Implicit conversions added to ease transition.
* `ToBitmapOptions`, `ToDataUrlOptions`, `ToPngOptions` & `BitmapOptions` have been consolidated into `ImageOptions`. Implicit conversions …
> Conversion to use ImageSharp rather than System.Drawing.Common

- ElectronNET.API/WindowManager.cs
**adds if missing**
missing part|default value that gets added
-------------|---------------
protocol     | `http://`
host            |`localhost`
port            | BridgeSettings.WebPort
> changed the processing of loadUrl at CreateWindowAsync

- ElectronNET.API/Entities/WebPreferences.cs
In the original Electron.js, ZoomFactor is a double, not an int.
See #754 for more info.
> Change WebPreferences.ZoomFactor from int to double

- ElectronNET.API/Dialog.cs
When selecting a path with special characters, they might get removed by the folder selection C#-side (see issue https://github.com/ElectronNET/Electron.NET/issues/735).
They are URL-decoded inside the ShowOpenDialogAsync method, which doesn't make sense: the decoding, if applicable, should be the responsibility of the JS side.
It's clearly not mandatory because other "dialog" methods, such as ShowSaveDialogAsync, don't use this UrlDecode and work fine.
This PR removes the URL decoding.
Re-creation of PR #736
> Fixes issue #735 - paths are URL escaped

- src/ElectronNET.CLI/Commands/Actions/GetTargetPlatformInformation.cs
The platform information will detect whether the process is x64 or arm64 and will report correct runtime ID to the publish command.
This PR resolves #820.
> Added OSX architecture detection

- src/ElectronNET.API/Entities/Display.cs
As you can see [here](https://www.electronjs.org/docs/latest/api/structures/display), the current Display.cs file in Electron.NET is not up to date. I've added all the missing fields (except for those which show up in the docs, but do not actually appear in the object we fetch from electron), and checked locally to see that it works.
One thing to note is that I did not change the `Id` value from `string` to `int`, because that caused the `Electron.Screen.GetAllDisplaysAsync()` method to hang forever, and changing it also means breaking backwards compatibility.
> Update Display.cs to current spec

- src/ElectronNET.API/IpcMain.cs
My app uses `IpcMain.Once` to wait for an "all good, next frame" message from the front end. It's updating data at rates well over 60fps, so I'm calling `IpcMain.Once` a lot. I noticed that since I started doing this, my memory usage went waaay up (from 40-50Mb to about 800Mb), so I started investigating memory dumps, and indeed, I found this object:
Which I later traced to be the object holding all of the socket listeners.
To fix this issue, all I had to do was replace the `Socket.On` in `IpcMain.Once` with `Socket.Once<object>`, and my memory usage went back down to 40-50Mb.
> Fix huge memory waste in IpcMain.Once [IMPORTANT]

- src/ElectronNET.API/WebContents.cs
- src/ElectronNET.Host/api/webContents.js
- src/ElectronNET.Host/api/webContents.ts
I just needed these for porting an existing Electron app to Electron.NET.
> WebContents: add executeJavaScript and dom-ready event

- src/ElectronNET.API/Entities/Point.cs
- src/ElectronNET.API/Entities/Rectangle.cs
- src/ElectronNET.API/Entities/Size.cs
This pull request adds implicit conversions from the following types:
* `Point`
* `Rectangle`
* `Size`
> Implicit Conversions to System.Drawing structs

- src/ElectronNET.Host/package-lock.json
Update node modules packages with the `npm audit fix` command
See the log below with vulnerabilities:
```
electron  23.0.0-alpha.1 - 23.3.13
Severity: moderate
Electron vulnerable to out-of-package code execution when launched with arbitrary cwd - https://github.com/advisories/GHSA-7x97-j373-85x5
Electron context isolation bypass via nested unserializable return value - https://github.com/advisories/GHSA-p7v2-p9m8-qqg7
ASAR Integrity bypass via filetype confusion in electron - https://github.com/advisories/GHSA-7m48-wc93-9g85
fix available via `npm audit fix`
node_modules/electron
engine.io  5.1.0 - 6.4.1
Severity: moderate
engine.io Uncaught Exception vulnerability - https://github.com/advisories/GHSA-q9mw-68c2-j6m5
fix available via `npm audit fix`
node_modules/engine.io
semver  <=5.7.1 …
```
> Update node modules packages

- .github/workflows/ci.yml
- nuke/Build.cs
- src/ElectronNET.API/ElectronNET.API.csproj
- src/ElectronNET.CLI/ElectronNET.CLI.csproj
.NET6 support is valid until [November 12, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy), more than half a year, I'm not sure this is a good idea to abandon .NET6 support in Electron.NET.
I would like to suggest making the project multitarget and support both LTS versions (.NET6 and .NET8)
dotnet tool doesn't support self-contaied tools (see https://github.com/dotnet/sdk/issues/9565), so that `<PublishSelfContained>true</PublishSelfContained>` can be useful only for binaries but not for dotnet tool so I decided to remove the line
> Get back net6 support
